[project]
name = "mvd"
version = "0.1.0"
description = "Multi-View Diffusion"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.3.0",
    "diffusers>=0.32.2",
    "icecream>=2.1.4",
    "torch>=2.6.0",
    "torchaudio>=2.6.0",
    "torchvision>=0.21.0",
    "transformers>=4.48.3",
]
