# Model parameters
architecture: stabilityai/stable-diffusion-2-1
torch_dtype: float32
use_memory_efficient_attention: true
enable_gradient_checkpointing: true

save_checkpoint_interval: 2  # Save every 2 hours
checkpoint_path: null        # Path to checkpoint to resume from

# Feature toggles for debugging
use_camera_embeddings: true
use_image_conditioning: true

# Training parameters
learning_rate: 0.00001
epochs: 100
batch_size: 4
val_check_interval: 0.5  # Check every x epochs
gradient_accumulation_steps: 32
max_grad_norm: 1.0
early_stopping_patience: 20
max_checkpoints: 5
sample_interval: 10

# Dataset parameters
dataset: Objaverse
image_size:
- 768
- 768
max_views_per_object: 8
max_samples: 10000       # null for full dataset
num_gpus: 1

# Loss weights
noise_weight: 1.0
latent_recon_weight: 0.5
pixel_recon_weight: 1.0
perceptual_weight: 0.1
ssim_weight: 0.1
geometric_weight: 0.2

# Debug parameters
debug: false
debug_num_sequences: 2
debug_max_pairs: 5