# Experiment tracking
version: v1
note: "changed denoising formula, added debug prints"

# Model parameters
architecture: stabilityai/stable-diffusion-2-1
torch_dtype: float32
use_memory_efficient_attention: true
enable_gradient_checkpointing: true

# Conditioning parameters
img_ref_scale: 0.2
cam_modulation_strength: 0.1

# Training parameters
num_gpus: 2
num_workers: 32
learning_rate: 0.000005
epochs: 20
batch_size: 5

val_check_interval: 0.5      # Check every x epochs
gradient_accumulation_steps: 4
max_grad_norm: 1.0
early_stopping_patience: 20
max_checkpoints: 10
sample_interval: 10
save_checkpoint_interval: 1  # Save every 1 hour
checkpoint_path: null        # Path to checkpoint to resume from

# Dataset parameters
dataset: Objaverse
image_size:
- 768
- 768
max_views_per_object: 8
max_samples: 1000       # null for full dataset

# Feature toggles for debugging
use_camera_embeddings: true
use_image_conditioning: true